audit_header: false
title: Madison Area Real Estate Journal
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: true
custom_links:
  - title: About
    url: https://jdholt.kw.com/meet-joshua-holt/
#   - title: Testimonials
#     url: /testimonials/   
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Joshua Holt
  title:
  license_number:
  about_markdown: |
    I am an eternal optimist with a passion for educating people which is what has led me to the Real Estate industry. In all my experiences, it is hard to top that moment when you have helped someone achieve their dream of home ownership or being able to improve upon their situation via the sale of a home.
  brand: Holt Real Estate Team
  brokerage: Keller Williams
  market: Madison Area
  address: 200 River Pl 130 Monona, WI 53716
  phone: 608-345-6594
  phone_type:
  phone2:
  phone2_type:
  email: jdholt@kw.com
  url: https://jdholt.kw.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: https://jdholt.kw.com/listings-search/#/2033763787

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://jdholt.kw.com/listings-search/#/2033763787

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/holtrealestateteam/
  linkedin_url: https://www.linkedin.com/in/joshua-d-holt/
  youtube_url: http://www.youtube.com/channel/UCADQ0F3qENM3ACWn5EL_X4w/featured
  twitter_url: https://twitter.com/JoshuaHoltRE
  instagram_url: http://instagram.com/holtrealestateteam/
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/Joshua-D-
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 100
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#fff'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#374C9E'
  theme_color: '#232628'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 2px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
